#!/usr/bin/env python

import os

VariantDir('build', 'src')
GTEST_HOME = '/home/colin/Git/googletest/googletest'
GTEST_INCLUDE = os.path.join(GTEST_HOME, 'include')

testEnv = Environment( #
        Env = os.environ,
        CCFLAGS='-g3 -Wall -I %s' % (GTEST_INCLUDE),
        CFLAGS='-fprofile-arcs -ftest-coverage',
        LINKFLAGS='-fprofile-arcs -ftest-coverage',
        LIBPATH=GTEST_HOME,
        LIBS=['libgtest', 'pthread']
)

sources = ['build/add.c']
testSources = ['build/add_test.cc']

testProg = testEnv.Program('a.out', sources + testSources)
testReport = testEnv.Command('test_report.xml',testProg,
        "./a.out --gtest_output=xml:${TARGET}")
coverageReport = testEnv.Command('coverage.xml', testReport,
        "gcovr -x -r build -o ${TARGET}")

Default(coverageReport)
