// 获得错误码
function getErrorNum(id){
	if(errorEnum != null && errorEnum[id] != null){
		return errorEnum[id];
	}
	return 100;
};

var errorEnum = {
	"server_error":100,
	"request_illegal":1001,
	"user_not_login":1002,
	"parameter_illegal":1003,
	
	"phone_number_illegal":101,
	"phone_number_be_used":102,
	"validation_times_too_many":103,
	"message_validation_error_times_too_many":104,
	"register_message_times_too_many":105,
	"send_message_too_frequent":106,
	"captcha_error":107,
	"captcha_invalid":108,
	"captcha_illegal":109,
	"message_validation_error":111,
	"request_times_too_many":112,
	"cookie_not_open":113,
	
	"detail_information_be_submitted":130,
	"country_illegal":131,
	"realname_different":132,
	"birthdate_illegal":133,
	"passport_illegal":134,
	"idnumber_illegal":135,
	"idnumber_invalid":136,
	"idnumber_be_used":137,
	"realname_illegal":138,
	"family_name_illegal":140,
	"name_illegal":141,
	"postcode_illegal":142,
	"province_illegal":143,
	"city_illegal":144,
	"street_illegal":145,
	"build_illegal":146,
	"unit_illegal":147,
	"limit_some_country":148,
	"younger_18_age":149,
	"postcode_isempty":150,
	
	"userbalancebean_not_found":161,
	"newpwd_illegal":162,
	"newpwd_different":163,
	"originpwd_empty":164,
	"originpwd_error":165,
	"loginpwd_tradepwd_equal":166,
	"safety_verification_not_set":167,
	"googel_verification_limit":168,
	"googel_verification_illegal":169,
	"googel_verification_error":170,
	"googel_verification_reuse":171,
	"message_verification_limit":172,
	"message_verification_illegal":173,
	"message_verification_error":174,
	"useroperator_failure":175,
	"modifypwd_failure":176,
	
	"tradepwd_verification_error":177,
	"tradepwd_verification_limit":178,
	"tradepwd_not_set":179,
	"is_not_level2":180,
	"user_be_delete":181,
	"not_bind_phonr_or_google":182,
	"email_not_bind":183,
	"phone_not_bind":184,
	"tradepwd_verification_illegal":185,
	"email_success":186,
	"email_fail":187,
	"email_customer_commit":188,
	"subuser_be_delete":189,
	
	"recharge_money_too_little":151,
	"recharge_information_not_complete":152,
	"remark_be_used":153,
	"recharge_order_not_find":154,
	"recharge_receive_not_find":155,
	"recharge_order_abnormal":156,
	
	"withdrawal_be_frezen":201,
	"future_risk_right":202,
	"lastticker_not_get":203,
	"account_hava_loan":204,
	"wait_six_confirm":205,
	"withdraw_info_not_set":206,
	"name_not_match":207,
	"withdraw_balance_over_50000":208,
	"bank_account_too_slow":209,
	"withdraw_balance_too_little":210,
	"withdraw_balance_too_much":211,
	"withdraw_balance_over_day_limit":212,
	"account_balance_too_little":213,
	"user_operator_1_day":214,
	"withdraw_address_not_get":215,
	"withdraw_address_not_verify":216,
	"withdraw_transaction_id_illegal":217,
	"withdraw_service_fee_too_much":218,
	"withdraw_service_fee_too_little":219,
	"withdraw_balance_illegal":220,
	"withdraw_balance_less_service_fee":221,
	"withdraw_balance_less_total":222,
	"withdraw_address_be_delete":223,
	"withdraw_coin_illegal":224,
	
	"not_bind_identity":241,
	"sub_user_can_not_operate":242,
	"sub_user_be_frezen":243,
	"recharge_address_illegal":244,
	"recharge_address_corract":245,
	"recharge_bank_illegal":246,
	"recharge_address_be_bind":247,
	"recharge_address_count_too_much":248,
	"withdraw_address_illegal":249,
	"withdraw_address_corract":250,
	"withdraw_bank_illegal":251,
	"withdraw_address_be_bind":252,
	"withdraw_address_count_too_much":253,
	"not_can_operate_auth_address":254,
	"withdraw_address_id_illegal":255,
	"withdraw_account_name_illegal":256,
	"withdraw_account_type_illegal":257,
	"withdraw_account_limit":258,
	"withdraw_account_not_get":259,
	"withdraw_account_have_bind":260,
	"withdraw_address_empty":261,
	"withdraw_payee_illegal":262,
    "withdraw_address_company_province_illegal":263,
    "withdraw_address_company_city_illegal":264,
    "withdraw_address_company_subbank_name_illegal":265,

	"weixin_get_qrcode_ticket_fail":501,
	"weixin_have_login":502,
	"weixin_sceneid_invalid":503,
	"weixin_openid_invalid":504,
	"weixin_user_info_not_get":505,
	"weixin_not_login":506,
	"weixin_have_bind_user":507,
	"weixin_not_bind_user":508,
	"weixin_user_be_bind":509,
	"weixin_bind_fail":510,
	"weixin_register_fail":511,
	
	"app_scan_have_login":541,
	"app_scan_code_invalid":542,
	"app_scan_userid_invalid":543,
	"app_scan_state_error":544
	
	
}