var languageJson = {
    "accountbeenfrozen": "该用户已被冻结！",
    "accountfrozen": "账户出现安全隐患已被冻结，请尽快联系客服！",
    "accountfrozencontactcustomer": "您的账户已被冻结，请联系客服！",
    "accounthasbeenfrozen": "该用户被冻结！",
    "accounthasopenloans": "账户有借款，请撤消借款或者还清借款后提现。",
    "accountlockedsecurityreasons": "账户出现安全隐患已被冻结，请尽快联系客服处理",
    "addmarginexplain1": "您正在开启自动追加保证金，当您持有的合约仓位爆仓时，会自动将您<b>现货账户</b>中的BTC/LTC转入至合约账户充当保证金，如果追加规则规定额度后仍然爆仓，则不再追加。这将降低您被爆仓强平的概率，但在极端情况下可能会导致您合约和现货账户中的BTC/LTC全部损失。您确定要开启自动追加保证金功能吗？",
    "addmarginexplain2": "您正在关闭自动追加保证金，将会在您账户达到强平线时进行强平，当前所持合约将锁定亏损，无法再盈利或减少亏损。您确定要关闭自动追加保证金吗？",
    "adminandlogincantmatch": "资金密码与登录密码不能相同！",
    "allpositionclose": "该仓位已经全平，不能重复操作！",
    "alreadywithdrawnaddress": "您已经存在提现地址，不允许再次添加",
    "amountnotbenull": "划转数量不能为空！",
    "amounttohigher100w": "数量不能大于1000000！",
    "amounttohigher10w": "数量不能大于100000！",
    "ensureexpottoexcel": "一次导出的记录上限为2000条，是否导出？",
    "applysuccess": "申请成功",
    "withdrawapplysuccess": "申请成功",
    "areyousureremittedus": "您确定已经登录网银给我们汇款了么？",
    "askprice": "卖出价",
    "overview":"合约账单",
    "historyorder_short":"历史委托",
    "nodealorders":"未成交委托",
    "indexNoData": "暂无数据",
    "atleastone": "请先增加一条再删除",
    "cancelAllFutureComfirm": "您确定撤销所有普通委托单吗？(不含策略交易)",
    "attemptsleft": "次机会",
    "available1": "可用",
    "availablecnyisinsufficient": "可用USD不足，无法完成提现操作",
    "availableopenlong": "可开多合约数: ",
    "availableopenshort": "可开空合约数",
    "future_available_openup": "可开",
    "availabletowithdraw": "可提取的",
    "balanceinsufficient": "您的余额不足！",
    "balanceisinsufficient": "您的余额不足，请先充值",
    "bankaccountcannotempty": "账户名称不能为空！",
    "bankaccountnumber": "银行卡账号",
    "bankaccountsnotmatch": "两次输入的帐户不一致",
    "benificiaryaddress": "账户地址",
    "otcNotice": "您的委托价与当前市场价格偏离超过10%，请确认委托价格与方向是否正确。",
    "otcNoticeSelect": "您选中的委单价格与当前市场价格偏离超过10%，请确认委托价格与方向是否正确。",

    "between": "之间！",
    "bidprice": "买入价",
    "dealDetilMsgBtc":"当用户的保证金率小于等于0%时（全仓），或用户某合约某方向某杠杆仓位的保证金率小于等于0%时（逐仓），将会促发爆仓强平。<br/>用户触发强平后，将按照保证金为0%的价格（$price）委托入市场，并按照该委托价格结算仓位的收益，但仓位平仓的实际成交价格可能不等于委托价格。若实际成交价格高于或低于委托价格，则成交价和委托价的差价部分将加入风险准备金。<br>风险准备金为OKCoin虚拟合约预防分摊风险的准备基金，当交割结算由于存在未成交爆仓单而导致穿仓损失时，将优先以风险准备金的余额承担穿仓损失。",
    "dealDetilMsgLtc":"当用户的保证金率小于等于0%时（全仓），或用户某合约某方向某杠杆仓位的保证金率小于等于0%时（逐仓），将会促发爆仓强平。<br/>用户触发强平后，将按照保证金为0%的价格（$price）委托入市场，并按照该委托价格结算仓位的收益，但仓位平仓的实际成交价格可能不等于委托价格。若实际成交价格高于或低于委托价格，则成交价和委托价的差价部分将加入风险准备金。<br>风险准备金为OKCoin虚拟合约预防分摊风险的准备基金，当交割结算由于存在未成交爆仓单而导致穿仓损失时，将优先以风险准备金的余额承担穿仓损失。",
    "lookBond":"查看风险准备金",
    "blindmoretime": "尝试次数过多，请您2个小时之后再验证手机!",
    "blindemailmoretime": "尝试次数过多，请您2个小时之后再验证邮箱地址!",
    "blindphonejs1": "该手机号已存在",
    "blindphonejs10": "您还有1次机会",
    "blindphonejs11": "谷歌验证码错误多次，请2小时后再试！",
    "blindphonejs12": "谷歌验证码错误！",
    "blindphonejs13": "您还有1次机会",
    "blindphonejs14": "设备添加成功！",
    "dealDetil": "成交详情",
    "blindphonejs15": "暂未添加谷歌身份认证，不能开启手机短信验证",
    "blindphonejs16": "暂未添加手机短信验证，不能开启谷歌身份认证",
    "blindphonejs17": "更改安全中心设置",
    "blindphonejs18": "验证修改成功！",
    "blindphonejs19": "未绑定谷歌",
    "blindphonejs2": "短信验证码不合法",
    "blindphonejs20": "未开启短信验证，不允许关闭谷歌！",
    "blindphonejs21": "未绑定手机",
    "blindphonejs22": "未开启谷歌 不允许关闭手机",
    "blindphonejs23": "谷歌身份验证器",
    "blindphonejs24": "查看谷歌认证密钥",
    "blindphonejs25": "暂未开启手机，不能关闭谷歌验证码",
    "blindphonejs26": "暂未开启谷歌验证，不能关闭短信验证码",
    "blindphonejs27": "暂未绑定手机，不能开启短信验证码",
    "blindphonejs28": "更改登录谷歌验证",
    "blindphonejs29": "更改双重验证方式",
    "blindphonejs3": "谷歌验证码不合法",
    "blindphonejs30": "验证码不正确！",
    "blindphonejs31": "请输入正确手机号",
    "blindphonejs32": "旧手机验证码不合法",
    "blindphonejs33": "新手机验证码不合法",
    "blindphonejs34": "修改手机验证码错误！",
    "blindphonejs35": "绑定手机验证码错误！",
    "blindphonejs36": "绑定手机验证码错误多次，请2小时后再试！",
    "blindphonejs37": "修改验证码错误！",
    "blindphonejs38": "您还有2次机会",
    "blindphonejs39": "没有绑定手机",
    "blindphonejs4": "手机号绑定成功！",
    "blindphonejs40": "新手机号已存在",
    "blindphonejs41": "手机号修改成功！",
    "blindphonejs42": "新手机号不能为空",
    "blindphonejs43": "您没有绑定手机",
    "blindphonejs44": "请求超时",
    "blindphonejs45": "暂未添加谷歌身份认证，不能开启谷歌身份认证",
    "blindphonejs46": "暂未添加手机短信验证，不能开启手机短信验证",
    "blindphonejs47": "修改成功！",
    "blindphonejs5": "已经绑定过手机",
    "blindphonejs6": "手机号已被绑定",
    "blindphonejs7": "手机号不合法",
    "blindphonejs8": "短信验证码错误多次，请2小时后再试！",
    "blindphonejs9": "短信验证码错误！",
    "changetwomodifyway":"更改双重验证方式",
    "viewgoogleauthenticatorkey":"查看谷歌认证密钥需要进行身份验证后才能继续，请输入",
    "bordersuccess": "计划委托成功！",
    "borrow": "借款",
    "busy": "系统正在交割，暂停交易。",
    "cacheTime":"交割结算后15分钟内，合约账户暂不能转出。",
    "buyamount": "购买数量",
    "buyamountrequired": "购买总金额不能为空！",
    "buyin": "买入",
    "buypricenotnull": "买入保护价格不能为空！",
    "buyproportion": "买入比例",
    "buyquantityrequired": "购买总数量不能为空！",
    "buytotalprice": "总金额",
    "buytradejs1": "您的余额不足，请先充值",
    "buytradejs10": "资金密码错误五次，请2小时后再试！",
    "buytradejs11": "资金密码不正确！",
    "buytradejs12": "",
    "notipnexttime": "下次不再弹出此提示（可在通知设置中重新开启）",
    "notipnexttimefulltrade": "下次不再弹出此提示（可在通知设置中重新开启）",
    "buytradejs13": "出价不能为0！",
    "buytradejs14": "余额不足！",
    "buytradejs15": "您未设置资金密码，请设置资金密码。",
    "buytradejs16": "您输入的价格与最新成交价相差太大，请检查是否输错",
    "buytradejs17": "资金密码免输超时，请刷新页面输入资金密码后重新激活。",
    "buytradejs18": "下单成功！",
    "buytradejs19": "账户出现安全隐患已被冻结，请尽快联系客服。",
    "buytradejs2": "您的BTC余额不足",
    "buytradejs20": "爆仓冻结，暂时不能操作账户。",
    "buytradejs21": "最小购买@btc",
    "buytradejs22": "最小购买@ltc",
    "ltcBuyMin": "最小购买0.1ltc",
    "btcBuyMin": "最小购买0.01btc",
    "ltcSellMin": "最小卖出0.1ltc",
    "btcSellMin": "最小卖出0.01btc",
    "buytradejs3": "您的LTC余额不足",
    "buytradejs4": "请输入交易数量",
    "buytradejs5": "最小交易数量为:@LTC！",
    "buytradejs6": "最小交易数量为:@BTC！",
    "buytradejs7": "请输入价格",
    "buytradejs8": "最小购买数量为:@BTC！",
    "buytradejs9": "最小购买数量为:@LTC！",
    "callbackrequired": "回调幅度不能为空！",
    "cancelled": "已撤销",
    "cannotbeless": "最小",
    "cannotgreaterthan": "单次购买数量均值不能大于100000！",
    "cannotgreaterthanbtc": "单次卖出数量均值不能大于100BTC！",
    "cannotgreaterthanltc": "单次卖出数量均值不能大于100LTC！",
    "cannotgreatethan": "回调幅度不能大于99.99%，请修改。",
    "cannotgreatethantrack": "回调幅度不能大于5.0%，请修改。",
    "cannotlessthantrack": "回调幅度不能小于0.1%，请修改。",
    "cannotgreatethanice": "委托深度不能大于1%，请修改。",
    "cannotlessthanice": "委托深度不能小于-1%，请修改。",
    "singleavelimited":"单笔均值范围",
    "contracts":"张",
    "advanceOpenSetting":"高级设置",
    "advanceCloseSetting":"关闭高级设置",
    "futureweituoem":"委托深度为空",
    "futurejiageoem":"价格限制为空",
    "futureweiamountem":"委托总数为空",
    "enteravgamount":"请输入单笔均值",
    "continuous3most":"最多只能有六个未成交的冰山委托",
    "singleavetoobig":"单笔均值大于上限",
    "singleavgsmall":"单笔均值小于下限",
    "avgnotbigthana":"单笔均值不能大于委托总量",
    "havenoagreecontin":"没有同意合约冰山委托协议",
    "cannotxlasttrack": "买单需要低于最新成交价",
    "cannotdlasttrack": "卖单需要大于最新成交价",
    "cannotlessone": "下单数量不足1张，请重新选择！",
    "cannotlessthan": "回调幅度不能小于0.01%，请修改。",
    "initiative3most":"最多只能有六个未成交的时间加权委托",
    "havenoagreeinitia":"没有同意合约时间加权委托协议",
    "saodanfanweixiao1":"扫单范围不能大于1%，请修改。",
    "saodanfanweixiao05":"扫单范围不能小于0.5%，请修改。",
    "sweepratioxiao20":"扫单比例不能大于100%，请修改。",
    "sweepratioda1":"扫单比例不能小于1%，请修改。",
    "perorderlimit":"单笔上限范围 ",
    "timeintervalr":"委托间隔范围  5-120s",
    "danbishangxian":"单笔上限不能为空",
    "weituojiange":"委托间隔不能为空",
    "perordertooh":"单笔上限大于限制",
    "perordertoolow":"单笔上限小于限制",
    "weituodadanbi":"委托总数需大于单笔上限",
    "futureplanentrust2": "限价单",
    "cannotopenfurther": "您当前的保证金率低于$p%，不能继续加仓！",
    "cannotopenfurtherafter": "开仓后您的担保金率低于90%，不能继续加仓！<a href='javascript:void(0)' onclick='openFutureTransfer();' >立即划转</a>",
    "cannotplaceorder": "当前合约状态不能下单！",
    "chances3": "次",
    "chancesleft": "次机会",
    "chineseuserchoice": "若您是中国站用户，请前往<a href='https://www.okcoin.cn'>OKCoin.cn</a>登录。",
    "chooseadate": "请选择一个日期",
    "closelargercurrent": "平仓数量大于同方向持仓数量！",
    "closelong": "平多",
    "closeshort": "平空",
    "buylongup": "买入开多(看涨)",
    "sellshortlow": "卖出开空(看跌)",
    "sellshortlow2": "卖出开空",
    "buylong": "买入开多",
    "details":"查看",
    "none":"无",
    "sellshort": "卖出开空",
    "buyshort": "买入平空",
    "selllong": "卖出平多",
    "shortposition": "平仓",
    "useshortposition": "市价全平",
    "long": "多",
    "short":"空",
    "cancle": "取消",
    "shortdelivery":"买入交割",
    "closeallshort":"买入全平",
    "forcedliquidationbuy":"买入强平",
    "longdelivery":"卖出交割",
    "closealllong":"卖出全平",
    "longdelivery":"卖出交割",
    "forcedliquidationsell":"卖出强平",
    "closealllong":"卖出全平",
    "shortdelivery":"买入交割",
    "emptytaleentrust": "您暂时没有委托数据",
    "coincommonjs1": "提示",
    "coincommonjs10": "邮箱不能为空",
    "coincommonjs11": "密码不能为空",
    "coincommonjs12": "密码长度不能小于6！",
    "coincommonjs13": "手机号:",
    "coincommonjs14": "没有手机号？",
    "coincommonjs15": "用邮箱注册",
    "coincommonjs16": "请输入11位数字",
    "coincommonjs17": "电子邮箱:",
    "coincommonjs18": "没有电子邮箱？",
    "coincommonjs19": "用手机注册",
    "coincommonjs2": "关闭",
    "coincommonjs20": "请输入你的常用邮箱",
    "coincommonjs21": "手机号包含空格!",
    "coincommonjs22": "请您输入手机号!",
    "coincommonjs23": "手机号格式不正确",
    "coincommonjs24": "邮箱不能包含空格!",
    "coincommonjs25": "请您输入邮箱!",
    "coincommonjs26": "邮箱格式不正确,请重新输入",
    "coincommonjs27": "含有非法字符",
    "coincommonjs28": "邮箱长度应小于100个字符",
    "coincommonjs29": "请输入真实邮箱",
    "coincommonjs3": "取消",
    "coincommonjs30": "您的手机号已存在，如果这是您自己的手机号",
    "coincommonjs31": "请",
    "coincommonjs32": "联系QQ:2260505979",
    "coincommonjs33": "联系客服",
    "coincommonjs34": "邮箱已存在",
    "coincommonjs35": "请输入密码！",
    "coincommonjs36": "密码长度不能大于32！",
    "coincommonjs37": "再输入一遍新密码！",
    "coincommonjs38": "输入的密码不一致！",
    "coincommonjs39": "  这个邮箱名字可能不正确，您确定么？",
    "coincommonjs4": "用户名或密码错误",
    "coincommonjs40": "请填写真实邮箱",
    "coincommonjs41": "行情图表",
    "coincommonjs42": "最小提现金额为:",
    "coincommonjs43": "秒后可重发",
    "coincommonjs44": "发送验证码",
    "coincommonjs45": "为了您的账户安全，请绑定手机或设置谷歌身份验证器！如果您不绑定，您丢失密码后可能会对您的财产造成不必要的损失，本站概不负责。",
    "coincommonjs46": "前往安全中心",
    "coincommonjsapia": "为了您的账户安全，请绑定手机或设置谷歌身份验证器！如果您不绑定，您丢失密码后可能会对您的财产造成不必要的损失，本站概不负责。",
    "coincommonjs47": "请输入邮箱地址",
    "coincommonjs48": "请设置启用COOKIE功能",
    "coincommonjs49": "请正确输入谷歌验证码。",
    "coincommonjs5": "此ip登录频繁，请2小时后再试",
    "coincommonjs50": "登录验证错误多次，请2小时后再试",
    "coincommonjs51": "登录验证错误",
    "coincommonjs52": "",
    "coincommonjs53": "此谷歌验证码已使用,请稍后再试",
    "coincommonjs54": "发送语音验证",
    "coincommonjs55": "切换短信验证码",
    "coincommonjs56": "发送验证码",
    "coincommonjs57": "切换语音验证码",
    "coincommonjs6": "您还有2次机会",
    "coincommonjs7": "您的浏览器还未开启COOKIE,请设置启用COOKIE功能",
    "coincommonjs8": "账户出现安全隐患被冻结，请尽快联系客服。",
    "coincommonjs9": "邮箱格式不正确",
    "completeinformation": "请填写完整信息！",
    "confirmHigh": "请确认以目前允许的最高买入价格",
    "confirmLow": "请确认以目前允许的最低卖出价格 ",
    "contactcustomer": "必选参数异常，请联系客服人员！",
    "contactsellerconfirm": "请联系卖家确认充值！",
    "reqiredSetPasswd": "因为交易金额过大，为了保障您的资金安全，需要您设置短信验证码（谷歌验证码）。",
    "phoneTimerOut": "发送短信失败请稍后再试!",
    "contract": "张",
    "waitDeal": " 等待成交",
    "contractlong": "多头",
    "contractshort": "空头",
    "contractlong_1": "多",
    "contractshort_1": "空",
    "contractlong_2": "多头仓位",
    "contractshort_2": "空头仓位",
    "deleteaddress": "确定要删除此地址吗？",
    "depositfailed": "充值失败",
    "depositfailedcontact": "充值失败，请联系客服人员！",
    "depositfailedfrozen": "充值失败。该充值码当前为查询冻结状态，您非查询用户，不能进行充值！",
    "depositfailedused": "充值失败，该充值码已充值",
    "depositsuccessful": "您已成功充值",
    "depositunvaible": "该充值无效！",
    "depthrequired": "委托深度不能为空！",
    "depthtoolarge": "委托深度超出范围，请重新输入！",
    "didntsavewithdrawaladdress": "您没保存提现地址，不能修改",
    "donothavephoneorgooglelinkedaccount": "您没有绑定手机和谷歌验证",
    "donotresubmit": "不能重复提交！",
    "earning": "收益",
    "earningRate": "收益率",
    "elitelongposition": "做多账户比例",
    "eliteshortposition": "做空账户比例",
    "enteramout": "数量不能为空！",
    "entergooglecode": "请输入谷歌验证码",
    "enterholdersname": "请输入收款人姓名",
    "enterprice": "暂无对手价，请输入价格操作！",
    "entersmscode": "请输入短信验证码",
    "entertranpass": "交易密码未输入！",
    "entertransactionpassword": "请输入资金密码",
    "entertriggerprice": "请输入触发价格",
    "enterwithdrawalamount": "请输入提现金额",
    "enterwithdrawbankaccount": "请输入提现帐户",
    "entercorractaccount": "银行卡账号不能含有数字以外的特殊字符",
    "error_buy": "买入",
    "error_sell": "卖出",
    "evercancelled": "已撤销",
    "exceededdailywithdrawallimit": "您的提现金额已超过今日提现限额，请重新输入",
    "exceededdailywithdrawallimitbtc": "您的提币金额已超过今日提现限额，请重新输入",
    "exceededgooglecodeattempts": "谷歌验证码错误多次，请2小时后再试！",
    "exceededmaximumrequests": "请求过于频繁，请30分钟后重试。",
    "existlentunavailable": "借款(含预约借款)及保证金部分不能转入！",
    "failedattempts": "资金密码错误五次，请2小时后再试！",
    "feecantincludecharacters": "您输入的手续费有误，手续费不能包含字母，特殊符号！",
    "fillinbankcardx": "请设置银行卡提现信息",
    "filloutallinformation": "请填写完整信息！",
    "forcedliquidation": "爆仓冻结，暂时不能操作账户！",
    "forremitting": "进行汇款",
    "forum1countlimit": "新手一天只能发1次帖!",
    "forum2daylimit": "新手2天以后才可以发表主题",
    "forumcharacterslimit": "标题或内容包含非法关键字，请修改!",
    "forumcontentvalidate": "请完成标题或内容栏",
    "forumdatevalidate": "结束日期必须大于开始日期",
    "forumdays": "天前",
    "forumedit": "编辑",
    "forumeditetopic": "编辑主题",
    "forumeditpost": "编辑帖子",
    "forumendtimevalidate": "填写的结束时间范围格式不正确！The finish time format provided was incorrect",
    "forumerrorip": "填写的IP地址不正确！",
    "forumerrorusername": "输入的用户名不正确!",
    "forumhours": "小时前",
    "foruminputip": "请填写IP地址！",
    "forumintro": "版块介绍",
    "forumiplimit": "你所在的IP因有人恶意发帖被封",
    "forumiputepostorder": "请填写置顶顺序！",
    "forumiputepostordervalidate": "填写置顶顺序只能是数字！",
    "forumipvalidate": "IP地址只能是数字！",
    "forumlogininput": "请输入用户名或UID!",
    "forumloginlimit": "你所在的用户组无法进行此操作.&nbsp;请<a href='javascript:showlogin(0);'>登录",
    "forummakenewpostslimit": "你没有权限发表主题",
    "forumminutes": "分钟前",
    "forummodsuccess": "修改成功",
    "forumnewtopic": "发表主题",
    "forumnocodelimit": "请不要使用编码发帖!",
    "forumnoemptylimit": "回复内容不能为空",
    "forumnounameanduid": "不能同时输入用户名和UID!",
    "forumofficiallimit": "这是发布官方信息的版块，您没有权限发帖",
    "forumoperatelimit": "你没有权限操作此项",
    "forumpostdeleted": "贴子已删除",
    "forumpostmoved": "贴子已移动到目标版块",
    "forumquintessenceadd": "主题已设置为精华",
    "forumquintessenceremove": "精华已解除",
    "forumreplaylimit": "新手一天只能回复5次!",
    "forumreplaypost": "回复帖子",
    "forumreplaytopic": "回复主题",
    "forumreply": "回复",
    "forumreportemptylimit": "报告内容不能为空",
    "forumreportsuccess": "报告成功！",
    "forumselectblockip": "请选择要解除的IP地址！",
    "forumselectblockuser": "请选择要禁止的用户！",
    "forumselectpostdelete": "请选择要删除的贴子！",
    "forumselectrelevantaction": "请选择相关操作！",
    "forumselecttopicdelete": "请选择要删除的主题！",
    "forumselecttopickind": "请选择要分类的主题！",
    "forumselecttopicmove": "请选择要移动的主题！",
    "forumselecttopicoperate": "请选择要操作的主题！",
    "forumsetlevel": "请设置权限等级！",
    "forumsetpermsuccess": "用户权限设置成功！",
    "forumstartimevalidate": "填写的开始时间范围格式不正确！",
    "forumtopicchanged": "主题分类已更改",
    "forumtopiceremoved": "主题已解除置顶",
    "forumuidvalidate": "输入的UID只能是数字！",
    "forumusernamelimit": "用户名不能包含汉字!",
    "forumuserreportdelete": "请选择要删除的用户报告!",
    "forumverifycode": "请输入正确的验证码",
    "friday": "周五",
    "futureallmarket": "市价全平",
    "futureclose": "平仓",
    "futuredeliverycountdown": "交割倒计时",
    "futureforcastprice": "预估交割价",
    "futuredays":"天",
    "futurehours": "小时",
    "futureminutes": "分",
    "futuresaccountfrozen": "合约帐户已冻结！",
    "futuresbuy": "买",
    "futureseconds": "秒",
    "futuresopeninter": "虚拟合约持仓总量",
    "futuressell": "卖",
    "getsmsverificationcode": "发送验证码",
    "getverificationcodetimedout": "验证码获取超时，请稍后再试。",
    "givebid": "问题不存在或已被评价!",
    "go": "前往",
    "googlecannotempty": "谷歌验证码不能为空！",
    "googlecodealreadyused": "此谷歌验证码已使用,请稍后再试",
    "googlecodebeenused": "此谷歌验证码已使用,请稍后再试",
    "googlecodecantempty": "谷歌验证码不能为空！",
    "googlecodeformatincorrect": "谷歌验证码格式不正确",
    "googlecodeincorrect": "谷歌验证码错误！",
    "googlecodeisincorrect": "谷歌验证码错误",
    "googlecodesformatincorrect": "谷歌验证码格式错误！",
    "haveoutstandingloans": "您还存在借款未还清，暂不能提现！",
    "havephoneorgooglelinkedaccount": "您没有绑定谷歌或者手机不允许操作",
    "highestrequired": "最高买入价格不能为空！",
    "highnew": "高",
    "holding": "金额",
    "holdingamount": "数量",
    "iddocument_address": "请输入地址",
    "iddocument_addressbook": "请选择住址证明",
    "iddocument_addressbookext": "您选择的住址证明格式非法，目前只支持JPG,JPEG,PNG格式",
    "iddocument_birthday": "请输入出生日期",
    "iddocument_city": "请输入城市",
    "iddocument_content15": "您输入的内容太长，不能超过15个字符",
    "iddocument_content20": "您输入的内容太长，不能超过20个字符",
    "iddocument_content50": "您输入的内容太长，不能超过50个字符",
    "iddocument_country": "请输入国家",
    "iddocument_email": "请输入邮编",
    "iddocument_endday": "请输入到期日期",
    "iddocument_id": "请输入ID",
    "iddocument_idbackext": "您选择的ID背面图片文件格式非法，目前只支持JPG,JPEG,PNG格式",
    "iddocument_idnumber": "ID不符合要求",
    "iddocument_idnumber_exsit": "此证件号已经存在",
    "iddocument_idpicture": "请选择ID图片文件",
    "iddocument_idpictureext": "您选择的ID图片文件格式非法，目前只支持JPG,JPEG,PNG格式",
    "iddocument_lastname": "请输入姓",
    "iddocument_m1": "您选择的ID图片大小非法，文件不能超过3M",
    "iddocument_m2": "您选择的住址证明大小非法，文件不能超过3M",
    "iddocument_m3": "您选择的ID背面图片大小非法，文件不能超过3M",
    "iddocument_name": "请输入名",
    "iddocument_province": "请输入省份",
    "iddocument_startday": "请输入发布日期",
    "iddocument_submiting": "提交中",
    "insubmiting": "提交中",
    "inlogin": "登录中",
    "inreg": "注册中",
    "immediatelybuy": "买入",
    "immediatelysell": "卖出",
    "incorrectnumbs": "次！",
    "incorrectremain": "交易密码错误，剩余",
    "infonotbenull": "必填参数为空，请检查！",
    "informationrequired": "必填参数为空，请检查！",
    "inforsrequired": "必填参数为空或下单数量不足1张，请仔细检查！",
    "inforsrequiredoption": "必选参数为空，请仔细检查！",
    "insufficient": "不足",
    "insufficientbalance": "用户余额不足！",
    "insufficientfuturesaccount": "合约帐户余额不足！<a href='javascript:void(0)' onclick='openFutureTransfer();' >立即划转</a>",
    "insufficientspotaccount": "您的现货账户资金不足！",
    "insufficientyoursaccount": "您的合约账户资金不足！",
    "functionisnotavailable": "根据相关法律，您所在的国家或地区不能使用该功能。",
    "intervalbetween": "委托间隔应在1-600秒之间！",
    "intervalexceedslimit": "委托间隔超出限制,请重新输入！",
    "intervalrequired": "委托间隔不能为空！",
    "invalidusernamepassword": "用户名或密码错误",
    "js0.01LTC": "恭喜您~<br/>您获得 0.01 LTC。",
    "js0.1BTC": "恭喜您~<br/>您获得 0.1 BTC。",
    "js0.1LTC": "恭喜您~<br/>您获得 0.1 LTC！",
    "js1BTC": "恭喜您~<br/>您获得 1 BTC！",
    "js1LTC": "恭喜您~<br/>您获得 1 LTC！",
    "jsFinisRoateToday": "亲~<br/>您的抽奖机会已用完！",
    "jsGo2TradeCenter": "前往合约交易中心",
    "jsMiner": "亲~太酷了~<br/>您获得宙斯矿机！",
    "jsNoChanceToday": "亲~<br/>暂时没有抽奖机会！",
    "jsRoseonly": "恭喜您~<br/>您获得Roseonly鲜花！",
    "jsShareHeader": "#OKcoin国际站合约上线#开仓玩合约，阳光大普照，我在幸运大转盘中转出了",
    "jsShareTail": "小伙伴们快跟我一起来吧~参与活动，转出幸运！",
    "jsTomorrow": "明天再来试试吧！",
    "kline1_15AverageLine": "15均线",
    "kline1_5AverageLine": "5均线",
    "kline1_Friday": "周五",
    "kline1_Monday": "周一",
    "kline1_Saturday": "周六",
    "kline1_Sunday": "周日",
    "kline1_Thursday": "周四",
    "kline1_Tuesday": "周二",
    "kline1_Wednesday": "周三",
    "kline1_all": "所有",
    "kline1_close": "收盘",
    "kline1_high": "最高",
    "kline1_low": "最低",
    "kline1_open": "开盘",
    "kline1_price": "价格",
    "kline1_volume": "成交量",
    "kline1_volume1": "成交数量",
    "alreadDeall": "已完全成交:",

    "lend": "放款",
    "lendjs1": "还款金额不能为0",
    "lendjs10": "可借",
    "lendjs11": "放款账户",
    "lendjs12": "数量不能低于",
    "lendjs13": "费率不能低于",
    "lendjs14": "费率不能高于",
    "lendjs15": "借入数量超过最大值",
    "lendjs16": "根据市场行情波动和风控参数，已经暂时停止新的",
    "lendjs17": "BTC融币",
    "lendjs18": "LTC融币",
    "lendjs19": "",
    "lendjs2": "放款账户",
    "lendjs20": "您目前设置的借款日费率为",
    "lendjs21": "高于费率",
    "lendjs22": "最低费率",
    "lendjs23": "是否确定下单？",
    "lendjs24": "费率低于0.01%",
    "lendjs25": "您目前设置的放款日费率为",
    "lendjs26": "自2014年5月10日起，已暂停新的融资融币。仍有借款和放款的用户可以正常还款和收款。",
    "lendjs27": "请修改。",
    "lendjs3": "余额不足",
    "lendjs4": "公测中，仅供部分用户测试。",
    "lendjs5": "转入交易账户",
    "lendjs6": "转入放款账户",
    "lendjs7": "低于最低转入金额",
    "lendjs8": "账户出现安全隐患被冻结，请尽快联系客服。",
    "lendjs9": "您有借款订单未还清或撤销",
    "lendjs28": "拆单请求出错，请重新尝试。",
    "lendjs29": "您当前有未成交的大宗交易委托，请在成交后或者撤单后再进行融资融币操作。",
    "lendjs30": "借款金额超过最大借款额度，请调整借款金额后重试",
    "haveMargin":"您当前有尚未偿还的欠款，请在还款后再使用大宗交易!",
    "coupon1": "已选",
    "coupon2": "免息",
    "coupon3": "融资融币免息卷",
    "coupon4": "使用融资融币免息卷",
    "cnybalanceinsu": "人民币余额不足",
    "lessshortposition": "空头平均持仓比例",
    "lessthan": "转入或转出数量小于0",
    "leverageratiolimit": "超过可以更改杠杆率范围！",
    "leveragerationotchanged": "您目前合约账户有持仓，暂不能更改杠杆率！",
    "linkedphonegoogletoaccount": "",
    "login": "登录",
    "loseHope": "亲，不要气馁~",
    "lownew": "低",
    "marginprice": "保证金: ",
    "maximumfee": "最高手续费为",
    "maximumminerfee": "最高网络手续费为",
    "maximumwithdrawal100w": "最大提现金额为1000000！",
    "medium": "中",
    "minerfeedeductedfromwithdrawal": "手续费将从提现金额中扣除，实际提币金额为",
    "minimum1000": "最小充值金额为100元",
    "minimumcoinwithdrawal": "最小提币金额为:",
    "minimumfee": "最低手续费为",
    "minimumminerfee": "最低网络手续费为",
    "minimumofminwithdrawa": "小于最小提币金额",
    "minimumrequired": "最低卖出价格不能为空！",
    "minimumwithdrawa100": "最小提现金额为：￥100",
    "minimumwithdrawa100_com": "最小提现金额为：$15",
    "minimumwithdrawa15_com": "最小提现金额为：$15",
    "minimumwithdrawalq100yuan": "最小提现金额为100！",
    "monday": "周一",
    "moreTries0": "次机会",
    "moreTries1": "次机会",
    "morelongposition": "多头平均持仓比例",
    "muchtimewrongquery": "由于多次错误查询，您已被冻结查询，请2小时后尝试查询！",
    "mustbetween": "回调幅度应小于99.99%并大于0.01%，请重新输入！",
    "namesdontmatch": "提现姓名与实名姓名不符",
    "nofuturesaccount": "您没有暂时合约账户，请联系客服！",
    "nofuturesaccountnow": "您的合约账户不存在，请联系客服！",
    "noinformationaboutvendor": "暂无代理商相关信息！",
    "notavalidbtcaddress": "输入的地址不是一个合法的btc地址",
    "notavalidltcaddress": "输入的地址不是一个合法的ltc地址",
    "nothavephonelinked": "您没有绑定手机",
    "notices": "提示",
    "notloggedin": "您还未登录！",
    "notoperateown": "非本人充值操作！",
    "notprocesswithdrawal": "无法进行提币操作",
    "notrepeatedlyconfirm": "请勿重复确认！",
    "notyetagreed": "您尚未签署协议，暂不能使用该功能！",
    "okparta": "OK充值码A段",
    "oksure": "确定",
    "oopsmadeamistake": "您输入的网络手续费有误，网络手续费中不能包含字母，特殊字符！",
    "openlong": "开多",
    "openshort": "开空",
    "openlongs": "开多",
    "openshorts": "开空",
    "operationfailed": "操作失败，请刷新页面重试",
    "operationsuccess": "操作成功！",
    "orderplacesuccess": "下单成功！",
    "orderspricelargelastprice": "委托价或触发价格大于当前价格",
    "orderspricelesslastprice": "委托价或触发价格小于当前价格",
    "lastprice":"最新成交价:",
    "orderssuccess": "下单成功！",
    "ordersuccess": "委托成功！",
    "parametererror": "参数错误！",
    "passporttimeout": "交易密码免输超时！",
    "passwordjs1": "修改登录密码",
    "passwordjs10": "您没有绑定手机或谷歌验证暂不允许修改密码。",
    "passwordjs11": "修改",
    "passwordjs12": "设置成功",
    "passwordjs13": "修改成功",
    "passwordjs14": "新密码不合法！",
    "passwordjs15": "原密码不正确！",
    "passwordjs16": "谷歌验证码输入错误",
    "totpCodeError": "谷歌验证码不能为空",
    "phoneCodeError": "短信验证码不能为空",
    "passwordjs17": "短信验证码输入错误",
    "passwordjs18": "登录密码不允许与资金密码一致",
    "passwordjs19": "资金密码不允许与登录密码一致",
    "passwordjs2": "请输入原登录密码：",
    "passwordjs20": "您没有绑定手机或谷歌验证暂不允许修改密码。",
    "passwordjs3": "请输入新登录密码：",
    "passwordjs4": "请再输入一次密码：",
    "passwordjs5": "修改资金密码",
    "passwordjs6": "请输入原资金密码：",
    "passwordjs7": "请输入新资金密码：",
    "passwordjs8": "请再输入一次密码：",
    "passwordjs8new": "请再输入一次密码：",
    "passwordjs9": "两次输入密码不相同！",
    "passwordjs21": "设置资金密码",
    "passwordstrengthlow": "密码强度低",  
    "passwordstrengthmedium": "密码强度中",
    "percau": "A段",
    "placederror": "下单失败，请联系客服！",
    "placeordererror": "下单失败，请联系客服！",
    "pleaseenterprice": "价格不能为空！",
    "cannotlessone":"下单数量不足1张，请重新选择！",
    "pleaseentertheamount": "请输入金额",
    "pleaseenteryouremail": "请输入邮箱地址",
    "pleasegoto": "请去",
    "pleaseonlyenternumbers": "请输入数字，您输入的不是纯数字",
    "pleaseselectaaddress": "请选择一个地址!",
    "pleaseselectabank": "请选择银行",
    "positionnotexist": "用户持仓不存在，请联系客服！",
    "priceequalpredeterminedpriceyouset": "价格达到您设置的触发价格时，系统将自动按您设置的卖出数量下达市价委托单。",
    "priceequaltopriceyouset": "价格达到您设置的触发价格时，系统将自动按您设置的购买金额下达市价委托单。",
    "pricetohigher10w": "价格不能大于100000！",
    "pricetohigher9999": "价格不能大于9999！",
    "pricetoohight": "委托价格触发了限价规则! ",
    "pricetoolow": "委托价格触发了限价规则!",
    "planpricetoohight": "委托价格触发了限价规则!",
    "planpricetoolow": "委托价格触发了限价规则!",
    "planfuturenotopen": "没有同意合约计划委托协议",
    "trackfuturenotopen": "没有同意合约跟踪委托协议",
    "pushjs1": "行情图表",
    "futurefuture": "合约",
    "quantityrequired": "卖出数量不能为空！",
    "questionjs1": "请选择问题类型。",
    "questionjs10": "账户出现安全隐患已被冻结，请尽快联系客服。",
    "questionjs11": "一个用户一天只能提交10次。",
    "questionjs12": "请输入回复。",
    "questionjs13": "回复不能超过1000个字符。",
    "questionjs200": "回复不能超过200个字符。",
    "questionjs14": "未找到该问题或者该问题已经完成。",
    "questionjs15": "同一条问题的回复不能超过50条。",
    "questionjs16": "问题不存在或已被评价!",
    "questionjs2": "请输入正确的地址。",
    "questionjs3": "输入的地址不是一个合法的btc充值地址",
    "questionjs4": "输入的地址不是一个合法的ltc充值地址",
    "questionjs5": "重复数量输入不合法。",
    "questionjs6": "请输入问题描叙。",
    "questionjs7": "问题描叙不能超过1000个字符。",
    "questionjs8": "请输入姓名。",
    "questionjs9": "请输入正确的电话号码",
    "qinvalidfile": "您选择的文件格式不正确，目前只支持JPG,JPEG,PNG格式",
    "qnopicture":"请选择图片",
    "qfilesize":"您选择的图片大小不正确，文件不能超过3M",
    "qfilesize5":"您选择的图片大小不正确，文件不能超过5M",
    "imageuploading":"图片正在上传，现在不能确认提交",
    "firstaddressimagemustbeupload":"第一张住址证明图片必须上传",
    "passportnoupload":"护照认证未上传",
    "verifyhasbeenaccepted":"您已通过该验证，不能上传",
    "noimageuploaded":"未上传图片",
    "companyinvalidfile":"您上传的文件格式不正确，请将资料以 PDF、JPG、JPEG、PNG 格式上传",
    "companyfilesize":"您上传的文件过大，请将您的文件大小保持在 5 M 以下",
    "companyfilesize10":"您上传的文件过大，请将您的文件大小保持在 10 M 以下",
    "companyfilesize30":"您上传的文件过大，请将您的文件大小保持在 30 M 以下",
    "uploadsucceed":"上传成功，开始审核，请您耐心等待···",
    "uploading":"上传中···",
    
    "rangemustbetween": "委托深度范围应在0%-±0.5%之间！",
    "ratioexceedslimit": "扫单比例超出限制,请重新输入！",
    "rechargecodeacannotempty": "充值码A不能为空！",
    "rechargecodeacantempty": "充值码A段不能为空！",
    "rechargecodebcannotempty": "充值码B段不能为空！",
    "rechargecodebeenchecked": "该OK充值码一小时内有过查询记录，目前为查询冻结状态，暂无查询信息！",
    "rechargecodeincorrect": "充值码错误",
    "rechargecodeinvalid": "该充值码无效！",
    "rechargecodeisincorrect": "充值码错误，充值失败，您剩余2次机会",
    "rechargecodenotexist": "该充值码不存在！",
    "rechargecodeused": "该OK充值码已充值！",
    "rechargeusdamount": "金额不能为空.",
    "rechargeusdcancel": "取消充值成功.",
    "rechargeusdcertificate": "身份认证未通过，不能充值.",
    "rechargeusdcheck": "若未见新打开的支付页面，为已被浏览器拦截，请检查。",
    "rechargeusdfailure": "充值失败.",
    "rechargeusdillegal": "参数错误，非法请求.",
    "rechargeusdmaxlimit": "充值金额大于每日充值限制.",
    "rechargeusdsubfailure": "提交失败.",
    "rechargeusdsubmitted": "提交成功。请您到新打开第三方支付页面上进行支付。",
    "rechargeusdsubsuccess": "提交成功.",
    "rechargeusdsuccess": "充值成功.",

    "alipayrecharge1": "请输入支付宝账号",
    "alipayrecharge2": "请输入正确的支付宝账号",
    "alipayrecharge3": "最大充值金额为5000元",
    "alipayrecharge4": "创建汇款单成功",
    "alipayrecharge5": " 已经被绑定",
    "alipayrecharge6": "操作失败，请重试",
    "alipayrecharge7": "需要实名认证之后才可以进行绑定",
    "alipayrecharge8": "子账户不允许此操作",
    "alipayrecharge9": "参数错误",
    "alipayrecharge10": "新增失败，服务器异常",
    "alipayrecharge11": "最多可以绑定两个支付宝账户",
    "alipayrecharge12": "支付宝转账",
    "alipayrecharge13": "绑定支付宝账户",
    "alipayrecharge14": "添加成功",
    "alipayrecharge15": "支付宝充值功能异常",

    "recipientsnamenotvalid": "收款人姓名不合法",
    "reenteramount": "请重新输入金额",
    "reenterbanknumber": "请再次输入银行卡账号:",
    "remaining": "剩余",
    "remarkbeenused": "这个备注已经被使用！",
    "remittedever": "已汇出",
    "requiredbidamount": "买入金额不能为空！",
    "requiredinfo": "必选参数为空！",
    "resendin5sec": "秒后可重发",
    "riskinfonotavailable": "您当前的风险信息不存在，请联系客服！",
    "saturday": "周六",
    "section1": "1、关注OKCoin官方微博，评论+转发合约活动链接并@3位好友",
    "section2": "2、关注OKCoin官方微信，转发微信活动并截图发送至OKCoin公众号",
    "selectbanktype": "请选择银行类型",
    "selectwithdrawalmethod": "请选择提现方式",
	"notselectbank":"未选择银行",
	"accountnumberisnotvalid":"银行帐号不合法",
	"entervalidaccountnumber":"请输入正确的卡号",
	"accountnumberconfirmationdoesnotmatch":"确认账号不相同",
	"onlycanadd5bankaccounts":"只能绑定5个银行卡",
    "bindaccountnumbersucceed":"绑定成功",
    "bindaccountmustbindidentity":"需要实名认证之后才可以进行绑定",
    "accountmusthasexisted":"已经被绑定",
    "haveadded5bankaccounts":"已绑定了5个银行账户",
    "bindaccountnumberfailed":"绑定失败",
    "payeeillegal":"收款人名称不合法",
    "depositbankprovinceillegal":"开户省份未选择",
    "depositbankcityillegal":"开户城市未选择",
    "subbanknameillegal":"支行名称不合法",
	"pleaseselectbankaccount":"请选择充值银行卡",
	"maxrechargeamount":"最大充值金额为99999999！",
	"companyrechargeaccountinvalid":"您是企业用户，需要用企业银行卡进行充值",
    "sellamount": "卖出数量",
    "sellamountrequired": "卖出总数量不能为空！",
    "selleraccountnumber": "账号",
    "sellerusername": "户名",
    "sellout": "卖出",
    "sellpricenotnull": "卖出保护价格不能为空！",
    "sellproportion": "卖出比例",
    "selltotalprice": "兑换额",
    "selltradejs1": "最小卖出@btc",
    "selltradejs2": "最小卖出@ltc",
    "selltradejs3": "最小卖出数量为：@BTC！",
    "selltradejs4": "最小卖出数量为：@LTC！",
    "sessionexpired": "您的用户登录已过期，请重新刷新页面！",
    "setfundspass": "您没有设置资金密码，请设置资金密码！",
    "setfundspassword": "您没有设置资金密码，请设置资金密码。",
    "settheminerfee": "请设置网络服务费",
    "setwithdrawaladdress": "请设置提现地址",
    "setwithdrawaladdressbtc": "请设置提币地址",
    "signup": "注册",
    "singlebuyaveragenotnull": "单次购买数量均值不能为空！",
    "singleentrustbetween": "单笔委托上限应在1000-100000之间！",
    "singleentrustrequired": "单笔委托上限不能为空！",
    "singleentrustshould": "单笔委托上限应在",
    "singlesellaveragenotnull": "单次卖出数量均值不能为空！",
    "smscannotempty": "短信验证码不能为空！",
    "smscodecantempty": "手机验证码不能为空！",
    "smscodeformatincorrect": "短信验证码格式不正确",
    "smscodeisincorrect": "短信验证码错误",
    "smscodewrongmuchtime": "短信验证码错误多次，请2小时后再试！",
    "smsisincorrect": "短信验证码错误！",
    "sscodesformatincorrect": "短信验证码格式错误！",
    "startnotexceedend": "开始日期不能大于结束日期",
    "successful": "生成成功",
    "sunday": "周日",
    "surecancelwithdrawal": "确定撤销提现么？",
    "surecloseafter": "仓位按市价进行全部平仓吗? ",
    "sureclosepre": "您确认对 ",
    "suretodeposit": "是否确认充值！",
    "sureyoutoopenfundspassword": "确定要开启资金密码输入吗?",
    "sweepmustbetween": "扫单范围应在0-5%之间！",
    "sweepratio": "扫单比例不能为空！",
    "sweepratiobetween": "扫单比例应在0.1%-100%之间！",
    "sweepratioexceedslimit": "扫单范围超出限制，请重新输入！",
    "sweepratiorequired": "扫单范围不能为空！",
    "switchpositionerror0": "没有符合条件的仓位",
    "switchpositionerror1": "用户是空",
    "switchpositionerror5": "您当前有(BTC/LTC)持仓或者挂单，暂不能切换。",
    "switchpositionerror2": "您当前有BTC持仓或者挂单，暂不能切换。",
    "switchpositionerror3": "您当前有LTC持仓或者挂单，暂不能切换。",
    "switchpositionerror6": "切换仓位位置出错",
    "switchpositioninitstr2": "您确定切换至逐仓保证金吗？",
    "switchpositioninitstr1": "您确定切换至全仓保证金吗？",
    "switchpositionsuccess": "恭喜成功",
    "takeParty": "你可以通过以下方式参与转发活动：",
    "thecodeformatincorrect": "验证码格式不正确",
    "thedepositinvalid": "充值金额不合法",
    "thesecuritytab": "安全中心",
    "thursday": "周四",
    "tolinkyourphoneorgoogletoaccount": "绑定手机或谷歌验证后提现。",
    "tolinkyourphoneorgoogletoOTC": "绑定手机和谷歌验证后进行大宗交易",
    "toomanyincorrectattempts": "资金密码错误多次，请2小时后再试！",
    "topge": "张",
    "futuresopenj": "",
    "topjsdata": "时间:",
    "topper": "百分比",
    "toptraderindex": "交易精英趋向指标",
    "trade_entrust_ten_ask": "卖出",
    "trade_entrust_ten_bid": "买入",
    "trade_entrust_ten_cancel": "撤销",
    "trade_entrust_ten_cancelled": "已撤销",
    "trade_entrust_ten_fulfilled": "完全成交",
    "trade_entrust_ten_instant": "市价",
    "trade_entrust_ten_partfulfilled": "部分成交",
    "trade_entrust_ten_unfilled": "尚未成交",
    "trade_entrust_ten_cancelling": "撤单处理中",
    "trade_entrust_ten_unfulfilled": "未处理",
    "trade_entrust_ten_yhnoo": "您暂时没有未成交的挂单",
    "transactionpasswordcantempty": "交易密码不能为空！",
    "transactionpasswordisincorrect": "资金密码错误！",
    "transactionpasswordwrong": "资金密码不正确！",
    "transferfailed": "划转失败，请联系客服！",
    "transferintofuture": "转入合约账户",
    "transferintofutures": "转入合约账户",
    "transferoutfuture": "转出合约账户",
    "transferoutfutures": "转出合约账户",
    "tuesday": "周二",
    "twitterFutureNews": "OKCoin国际站合约上线啦~我参与了开仓玩合约，获得了“幸运转不停”的抽奖机会！超级好礼满盘转！小伙伴们快跟我一起行动起来吧！给力开仓！玩转合约！",
    "undo_error": "撤销失败，请联系客服！",
    "update": "系统正在升级，暂停交易。",
    "usdbankaddress": "银行地址",
    "usdcouldnotbeempty": "不能为空",
    "usdcouldnotpassthrough": "未通过等级2认证",
    "usdnameofbank": "银行名称",
    "useraccountfrozen": "您的帐户已冻结！",
    "userfuturesfrozen": "您的合约帐户已冻结！",
    "userindexjs1": "昵称不能超过10个字符",
    "userindexjs10": "邮箱验证未通过，链接仅15分钟有效",
    "userindexjs11": "请求过于频繁",
    "userindexjs12": "绑定邮箱不能为空！",
    "userindexjs13": "登录密码或确认密码不能为空！",
    "userindexjs14": "登录密码和确认密码不相同！",
    "userindexjs15": "验证码不能为空！",
    "userindexjs16": "邮箱，密码，确认密码，资金密码，验证码为空",
    "userindexjs17": "登录密码，确认密码不相同",
    "userindexjs18": "忘记密码？",
    "userindexjs19": "该邮箱已被使用，请使用其他邮箱！",
    "userindexjs2": "昵称不能包含特殊字符",
    "userindexjs20": "该用户已存在邮箱！",
    "userindexjs21": "没有绑定谷歌或者手机，不允许操作！",
    "userindexjs22": "校验邮箱失败，邮箱格式不正确！",
    "userindexjs23": "交易密码未设置，请先设置交易密码！",
    "userindexjs24": "邮件发送失败请重新点击发送",
    "userindexjs25": "邮箱错误，请确认后输入。",
    "userindexjs26": "用户请求过于频繁，请5分钟后再试",
    "userindexjs27": "验证码错误",
    "userindexjs28": "验证码错误多次请2小时候后再试",
    "userindexjs29": "确定关闭资金密码交易时免输吗？",
    "userindexjs3": "两次密码输入不一致",
    "userindexjs30": "修改成功",
    "userindexjs31": "请填写姓名",
    "userindexjs32": "两次输入的姓名不一致",
    "userindexjs33": "请填写证件号码",
    "userindexjs34": "请填写正确身份证号码",
    "userindexjs35": "证件号码不合法",
    "userindexjs36": "账户未设置安全验证",
    "userindexjs37": "为了防范资金密码泄露，保障您的账户资金安全，请前往安全中心设置资金密码。",
    "userindexjs38": "姓名字符过长",
    "userindexjs39": "证件号码过长",
    "userindexjs4": "短信验证码输入不合法",
    "userindexjs40": "出生日期不能为空",
    "userindexjs41": "街道不能为空",
    "userindexjs42": "街道字符过长",
    "userindexjs43": "省份不能为空",
    "userindexjs44": "省份字符过长",
    "userindexjs45": "国家不能为空",
    "userindexjs46": "国家字符过长",
    "userindexjs47": "邮编不能为空",
    "userindexjs48": "邮编字符过长",
    "userindexjs49": "城市不能为空",
    "userindexjs5": "谷歌验证码输入不合法",
    "userindexjs50": "城市字符过长",
    "userindexjs51": "邮编字符过短",
    "userindexjs52": "曾用名过长",
    "userindexjs6": "密码格式不合法",
    "userindexjs7": "资金密码不允许与登录密码一致",
    "userindexjs8": "登录密码不允许与资金密码一致",
    "userindexjs9": "用户未设置安全验证，不允许修改密码。",
    "sendagain": "重新发送",
    "sendagainlater": "s后重新发送！",
    "useup8decimalplaces": "小数点后面仅可以保留八位小数",
    "wednesday": "周三",
    "welfuturetrade": "恭喜您，您已经成功开通合约交易!",
    "whenthepriceof": "",
    "widthdrawlfailed": "提现失败!",
    "withdrawaladdr10": "一个人最多只允许有十个提现地址",
    "withdrawaladdr5": "一个人最多只允许有五个提现地址",
    "withdrawaladdresscannotempty": "提现地址不能为空！",
    "withdrawalamountcantempty": "提现金额不能为空！",
    "withdrawalamountisinvalid": "你输入的提币金额不合法，应该大于0！",
    "withdrawalbankaccountslow": "您所绑定的银行卡提现到账缓慢，我们建议您更换银行卡。",
    "withdrawalbankaccountslow2": "您所绑定的银行卡只支持单笔5W以内。",
    "withdrawalcantexceedbalance": "提现金额不能大于账户余额！",
    "withdrawalexceedsbalance": "取现金额大于账户剩余金额！",
    "withdrawalnotbeprocessed": "无法提币",
    "withdrawalnotbeprocessedover": "无法完成提现操作",
    "amountcannotempty":"输入金额不能为空",
    "notremittance":"未汇款",
    "withdrawalverifiedbankcardsuccess":"银行卡认证已成功！恭喜您通过身份认证，系统将自动完成您的提现请求，请耐心等待。",
    "verificationbankcardfailed2times":"您已经认证失败2次，请重新提交银行卡信息。",
    "verificationbankcardfailed":"认证失败，输入金额不匹配;您还有一次验证机会",
    "notuploadIDdocument":"验证资料未上传",
    "wrongmuchtimelater": "您的交易密码错误次数过多，请稍后再试！",
    "youcould": "您可以直接",
    "youhave": "您还有",
    "youhaveonly": "您剩余",
    "yuan": "元",
    "Short position":"空头",
    "Short position decrease":"空头",
    "Long position decrease":"多头",
    "counterspl":"切换收益",
    "countersplr":"切换收益率",
    "Long position":"多头",
    "withdrawAddressTipsChina":"该地址是OKCoin中国站地址，提币可0确认到账哦",
    "withdrawAddressTipsInternational":"该地址是OKCoin国际站地址，提币可0确认到账哦",
    "syncinfoerror1":"国际站已存在该账户，不能同步已存在用户。",
    "syncinfoerror2":"国际站已存在该手机号，不能同步已存在手机号。",
    "syncinfoerror3":"同步失败，请重试。",
    "syncinfoerror4":"登录密码错误。",
    "syncinfoerror5":"资金密码错误。",
    "syncinfoerror6":"子账户不能同步。",
    "foreignIdentityfirstname":"姓不能为空。",
    "foreignIdentityfirstnameislong":"姓字符过长。",
    "foreignIdentitylastname":"名不能为空。",
    "foreignIdentitylastnameislong":"名字符过长。",
    "foreignIdentitypreviousnameislong":"别名字符过长。",
    "foreignIdentityrealname":"本地语言姓名不能为空。",
    "foreignIdentityrealnameislong":"本地语言姓名字符过长。",
    "foreignIdentitybirthdate":"生日不能为空。",
    "foreignIdentitypassport":"护照号不能为空。",
    "foreignIdentitypassportislong":"护照号字符过长。",
    "foreignIdentitypassportisshort":"护照号字符过短。",
    "foreignIdentitystartdate":"护照发证日期不能为空。",
    "foreignIdentityenddate":"护照发证日期不能为空。",
    "foreignIdentitystartdatebigthanenddate":"请填写正确的护照时间。",
    "foreignIdentityidnumber":"身份证不能为空。",
    "foreignIdentityidnumberislong":"身份证字符过长。",
    "foreignIdentityidnumberisshort":"身份证字符过短。",
    "foreignIdentityprovince":"省份不能为空。",
    "foreignIdentityprovinceislong":"省份字符过长。",
    "foreignIdentitycity":"城市不能为空。",
    "foreignIdentitycityislong":"城市字符过长。",
    "foreignIdentitystreet":"街道不能为空。",
    "foreignIdentitystreetislong":"街道字符过长。",
    "foreignIdentitybuild":"建筑号不能为空。",
    "foreignIdentitybuildislong":"建筑号字符过长。",
    "foreignIdentityunit":"单元号不能为空。",
    "foreignIdentityunitislong":"单元号字符过长。",
    "registeringaccount":"#OKCoin送神秘大礼# 我在okcoin.com玩合约，邀请好友注册。不仅能抽iPhone6、XBOX，更能获得神秘大奖，赶快一起来吧！",
    "notEmptyRealName":"真实姓名不能为空。",
    "twiceEntryNotMatch":"两次输入的姓名不一致.",
    "notEmptyBirthday":"生日不能为空.",
    "notEmptyIdNumber":"身份证号不能为空.",
    "entryPassportNum":"请输入护照号.",
    "notEmptyIssuedDate":"发证日期不能为空.",
    "notEmptyExpiredDate":"失效日期不能为空.",
    "entryNameAgain":"请再次输入姓名",
    "wrongpassportnumber":"护照号码错误",
    "wrongidnumber":"身份证号错误",
    "idnumberisempty":"身份证已经被使用，请重新输入",
    "yearoldover":"本平台暂不支持60岁以上用户交易",
    "enterinvitecode":"请输入邀请码",
    "invitcode6":"邀请码小于6位，请重新输入",
    "invittry":"您的验证码有误，请重新输入!",
    "invitfailatt":"由于您多次输入错误，请于2小时后重试！",
    "invitsucc":"恭喜您，您已经成功开通联合理财产品!",
    "invithave":"您的验证码有误，剩余次数",
    "invitci":"次",
    "invit":"您已经开通联合理财产品！",
    "volumedatehour":"%e日%H时",
    "volumedateday":"%e日%H时",
    "validblcoin": "请输入一个合法的",
    "validbladdr": "地址",
    "validbaddr": "比特币",
    "validladdr": "莱特币",
    "copytoclip":"已成功复制到剪切板！",
    "addmarginexplain1_1":"您正在开启自动追加保证金，当您持有的合約仓位爆仓时，会自动将您<b>合约账户余额</b>中的BTC/LTC转入至合约账户余额充当保证金，如果追加规则规定额度后仍然爆仓，则不再追加。这将降低您被爆仓强平的概率，但在极端情况下可能会导致您和合约账户中的BTC/LTC全部损失。您确定要开启自动追加保证金功能吗？",
    "bankrecharge1":"请选择代理商",
    "bankrecharge2":"金额必须在100元到100万元之间",
    "bankrecharge3":"提交成功",
    "bankrecharge4":"金额重复，为了您的充值快速到账，请在现在金额上加小数，如1000.01元",
    "bankrecharge5":"大额汇款，可通过VIP通道快速充值",
    "bankrecharge6":"请在24小时内通过QQ提供充值ID，否则交易将被取消",
    "companyidentityjs1":"英文名太长",
    "companyidentityjs2":"注册日期不合法",
    "companyidentityjs3":"注册号太长",
    "companyidentityjs4":"请填写企业英文名称",
    "companyidentityjs5":"本地语言名称太长",
    "companyidentityjs6":"注册日期不能为空",
    "companyidentityjs7":"注册号不能为空",
    "companyidentityjs8":"本地语言名称不能为空",

    "companyidentityjs9":"股东",
    "companyidentityjs10":"股东类型",
    "companyidentityjs11":"个人",
    "companyidentityjs12":"公司",
    "companyidentityjs13":"根据OKCoin的规定，如果有股东是公司的话，需要您提供股东公司的董事及股份信息才能完成认证。",
    "companyidentityjs14":"持股比例",
    "companyidentityjs15":"姓（拼音）",
    "companyidentityjs16":"名（拼音）",
    "companyidentityjs17":"名称",
    "companyidentityjs18":"企业注册号",
    "companyidentityjs19":"资料上传",
    "companyidentityjs20":"选择文件",
    "companyidentityjs21":"添加股东",
    
    "companyidentityjs22":"董事一姓过长",
    "companyidentityjs23":"董事一名过长",
    "companyidentityjs24":"董事一信息不全",
    "companyidentityjs25":"董事二姓过长",
    "companyidentityjs26":"董事二名过长",
    "companyidentityjs27":"董事二信息不全",
    "companyidentityjs28":"请输入董事信息",
    "companyidentityjs29":"董事信息提交成功",
    "companyidentityjs30":"董事一信息过长",
    "companyidentityjs31":"董事二信息过长",
    "companyidentityjs32":"提交失败",
    "companyidentityjs33":"请输入持股比例",
    "companyidentityjs34":"持股比例错误",
    "companyidentityjs35":"持股比例小于10%",
    "companyidentityjs36":"持股比例过大",
    "companyidentityjs37":"请输入姓",
    "companyidentityjs38":"您输入的姓过长",
    "companyidentityjs39":"请输入名",
    "companyidentityjs40":"您输入的名过长",
    "companyidentityjs41":"请输入公司名称",
    "companyidentityjs42":"您输入的公司名称过长",
    "companyidentityjs43":"请输入公司注册号",
    "companyidentityjs44":"您输入的公司注册号过长",
    "companyidentityjs45":"请选择股东公司的资料文档",
    "companyidentityjs46":"提交成功",
    "companyidentityjs47":"提交出错",
    "companyidentityjs48":"持股比例不正确",
    "companyidentityjs49":"姓过长",
    "companyidentityjs50":"名过长",
    "companyidentityjs51":"公司名称过长",
    "companyidentityjs52":"公司注册号过长",
    "companyidentityjs53":"公司的资料文档未选择",
    "companyidentityjs54":"公司的资料文档类型不合法",
    "companyidentityjs55":"公司的资料文档过大",
    "companyidentityjs56":"提交失败",
    "companyidentityjs57":"上传失败",
    "companyidentityjs58":"董事信息必须提交",
    "companyidentityjs59":"股东信息必须提交",
    "companyidentityjs60":"提交失败",
    
    "companyidentityjs61":"请简要介绍一下贵公司的主要业务",
    "companyidentityjs62":"主要业务的介绍过长",
    "companyidentityjs63":"请简要介绍一下贵公司的资金来源",
    "companyidentityjs64":"资金来源的介绍过长",
    "companyidentityjs65":"请简要介绍公司接下来一年的交易计划",
    "companyidentityjs66":"交易计划的介绍过长",
    "companyidentityjs67":"公司介绍提交成功",
    "companyidentityjs68":"提交失败",
    "companyidentityjs69":"重新选择",
    "companyidentityjs70":"请选择pdf格式文件",
    "companyidentityjs71":"提交",
    "companyidentityjs72":"未提交",
    "companyidentityjs73":"持股比例总和超过100%，请检查股东信息",

    "companyidentityjs74":"别名（拼音）",
    "companyidentityjs75":"董事一别名过长",
    "companyidentityjs76":"董事二别名过长",
    "companyidentityjs77":"您输入的别名过长",
    "companyidentityjs78":"别名过长",

    "buypriceonepercent":"您当前买单价格高于卖一价1%，您是否确定下单？",
    "sellpriceonepercent":"您当前卖单价格低于买一价1%，您是否确定下单？",
    "addrtagtoolang":"标签过长，请重新设置",
    "savewithdrawaladdress":"保存提现地址",
    "savewithdrawaladdress1":"选择提现地址",
    "depth_buy":"买",
    "depth_sell":"卖",
    "open_depth":"合并深度：开",
    "open_depth2":"开",
    "close_depth2":"关",
    "close_depth":"合并深度：关",
    "uploadimgfirst":"请先上传图片",
    "settlewarming":"合约正在结算中",

    "resetPasswordAlert":"<h3 style='text-align: center;font-size:16px;color: #329ddc;'>重设资金密码</h3>为了您的资产安全，资金密码修改后24小时以内不允许提币，给您带来的不便，敬请谅解！",
    "userConforimSelect0":"您确定选择个人用户认证？",
    "userConforimSelect1":"您确定选择企业用户认证？",
    "active01BTC":"恭喜你！<br/>获得0.1BTC",
    "activezhengyibook":"恭喜你！<br/>获得《争议比特币》一本",
    "active1LTC":"恭喜你！<br/>获得1LTC",
    "active001BTC":"恭喜你！<br/>获得0.01BTC",
    "active01LTC":"恭喜你！<br/>获得0.1LTC",
    "activeiphone6":"恭喜你！<br/>获得iPhone6",
    "activexiaomi4":"恭喜你！<br/>获得小米4",
    "active1BTC":"恭喜你！<br/>获得1BTC",
    "active001LTC":"恭喜你！<br/>获得0.01LTC",
    "activeMac":"恭喜你！<br/>获得MAC一台",
    "withdrawalbefrezen":"您的提现操作因存在风险已被冻结，请联系客服。",
    "waitsixconfirm":"您有BTC/LTC充值，该部分等值金额需6个网络确认后方能提出。",
    "haveborrowmonty":"借款(含预约借款)及保证金部分不能提出。",
    "emailnotbind":"提币需要绑定邮箱后才能继续操作",
    "useroperator1day":"为了您的资金安全，在修改手机或者更换验证方式后24小时内不允许提现，如有此操作需求请联系客服。",

    "apiCreateSuccess":"新建apiKey成功",
    "apiUpdateSuccess":"修改apiKey成功",
    "apiDeleteSuccess":"删除apiKey成功",
    "error1001": "每个用户最多能够申请50个apiKey",
    "error1002": "没有查询到相关记录",
    "error1003": "新建apiKey失败",
    "error1004": "修改apiKey失败",
    "error1005": "删除apiKey失败",
    "error1006": "短信发送失败，请稍后再试",
    "error1007": "查询apiKey失败",
    "error1008": "备注名不能重复",
    "error1009": "备注名不能为空",
    "error1010": "备注名只能由中文汉字、大小写英文字母、数字组成",
    "error1011": "大宗交易需要验证手机和谷歌",
    "addressinfoloading": "地址信息加载中...",
    "addressinfoloadfail": "地址信息获取失败,请输入正确邮编地址",
    "inputrightpostcode": "请填写正确邮编",
    "inputrightpostcodenotnull": "邮编不能为空",
    "inputaddressinfodetail": "请填写详细地址",
    
    "openorderscanceled": "撤单成功",
    "noopenorders": "没有挂单",
    "ordersnotcanceled": "撤单失败",
    "purchasePackageAlert": "账户总资产小于该提现套餐额度，剩余额度到期后清零，确认购买？",
    "confirmamount":"确认支付",
    	
    "hold_profit":"当前未平仓仓位的收益，包括该仓位已经结算到用户余额中的已实现收益和最近一次结算后产生的未实现收益。",
    "hold_profit_rate":"收益率 = 收益 / 开仓时所需保证金。",
    "hold_unprofit":"用户未平仓的仓位的收益。在每周五下午合约结算时，用户仓位的未实现盈亏将会转入用户的余额，未实现盈亏归零后重新计算。",
    "hold_cost_price":"原成本价，系统用于计算用户未实现盈利的价格。在结算时，该价格会相应的进行调整。结算基准价的变动不会影响用户的实际收益。例如，用户在100元的价格做多，未结算时用户的结算基准价是100元，假设结算价是120元，则结算时系统会将用户仓位100元-120元区间的利润转换为已实现盈利并增加到用户的余额中，同时将用户的结算基准价调整为120元。",
    "hold_profit_loss_rate":"<p>逐仓：盈亏比 = 未实现盈亏 / 固定保证金</p><p>全仓：盈亏比 = 未实现盈亏 / 开仓时所需保证金</p>",
    "hold_profit_loss_rate_new":"保证金率 = (固定保证金+未实现盈亏) * 开仓均价 * 杠杆 / (合约面值 * 持仓数量) - 调整系数；10倍杠杆，BTC的调整系数=10%，LTC的调整系数=20%，20倍杠杆，BTC的调整系数=20%，LTC的调整系数=40%。",
    "hold_profit_finish":"表示当前仓位所持的合约通过结算已转入余额的收益。",

    "hold_unrealized":"未实现盈亏",
    "hold_cost":"结算基准价",
    "hold_plratio":"盈亏比",
    "hold_settledearnings":"已结算收益",
    "hold_fixmargin":"固定保证金",
    "hold_amount_error":"输入数量小于最小开仓数量",
    "hold_open":"展开",
    "hold_close":"收起",
    "hold_guaranteeRate":"保证金率",
    "foreignIdentitycannotverify":"我们暂不支持对该国家的公民提供服务",
    "withdrawalmustlevel2": "通过高级认证后才可以使用OK充值码提现",
     "hold_cny_change_exp":"实际交易价格已按美元计价，因美元汇率变动，人民币价格显示会相应变动。",
    "clawbackweekly": "当周",
    "clawbackmonthly": "季",
    "msgCodeBtnValue": "发送验证码",
    "clawbackall": "全部",
    "futurescreendownchrome":"当前浏览器版本不支持K线图显示，推荐换用Chrome浏览器（谷歌浏览器）<a href='http://rj.baidu.com/soft/detail/14744.html?ald'>下载</a>",
    "futureriskright":"由于您的合约账户权益小于0，暂不能提现，请联系客服进行提现操作",
    "pleasesetreserveamount":"请设置预留金额",
    "minlendamount":"最低放款金额不能小于",
    "autolendsetsuccess":"自动放款设置成功",
    "pleaseagreementrule":"您尚未同意放款协议.",
    "havenosignedthewrittenagreement":"根据法律法规，目前只允许已签订书面协议的用户放款",
    "autolendsetfail":"自动放款设置失败",
    "wrongparams":"错误的参数.",
    "reserveamountmustgt0":"预留金额不能小于0",
    "futureplan10error":"计划委托最多只能下10张单！",
    "futuretrack10error":"跟踪委托最多只能下10张单！",
    "averageorderamountbuy":"单次购买数量均值不能小于",
    "leverratefull_error":"LTC暂不支持20倍杠杆切换!",
    "inputrightphonenumber":"请输入正确的手机号",
    "enteraddressname":"请设置标签",
    "totalorderamountbuy":"购买总金额不能小于",
    
     "radioRateInputValue":"自定义",
     
     "subuseradd":"新增子账户",
     "subusertran":"资金划转",
     "subuserresetlogin":"重置登录密码",
     "subuserlock":"冻结子账户",
     "subuserunlock":"解冻子账户",
     "subuserdelete":"删除子账户",
     "subusermanger":"管理子账户",
     "subusererror":"操作失败",
     "subuseraddsu":"添加子账户成功，使用登录名和密码即可登录子账户。",
     "subuserinsertsu":"新增子账户成功",
     "subuseruppasssu":"修改用户密码成功",
     "subuserinpasssu":"更改子账户密码成功",
     "subusercantde":"该子账户有未转出的资产，暂不能删除该子账户",
     "subuserdelfail":"删除子账户失败",
     "subuserfreezesu":"子账户冻结成功",
     "subuserfreeze":"冻结子账户成功",
     "subuserunfrsu":"子账户解冻成功",
     "subuserunfreesu":"解冻子账户成功",
     "subuserupnick":"修改子账户备注",
     "subuserupnicksu":"修改子账户备注名成功",
     "subuserupsu":"修改子账户成功",
     "subuserpassill":"密码不合法",
     "subusernicknotem":"子账户备注名不能为空",
     "subusernickmax20":"备注名最多20位",
     "subusernotresend":"请不要重复提交",
     "subusernickill":"子账户备注名不符合规范",
     "subusernameem":"子账户登录名不能为空",
     "subusernamemax":"登录名只能是字母或数字，6至20位",
     "subusernamenum":"子账户登录名不能为纯数字，请修改。",
     "subusercount":"已创建的子账户(含删除)不能超过10个",
     "subuserexists":"该登录名已存在，改用其它登录名",
     "subuseralrfreeze":"该用户已经被冻结，操作失败",
     "subusertransu":"转账成功",
     "subuserenough":"转账失败，余额不足或账户已过期",
     "subuserinval":"转账失败，子账户无效",
     "subusernotyour":"转账失败，该账户不是您的子账户",
     "subusercantwith":"转账失败，您的提现操作被冻结",
     "subusernotsafe":"转账失败，转账后剩余资金超出安全范围",
     "subusertranfail":"转账失败",
     "subuserfreezebyyou":"转账失败，该账户已被您冻结",
     "subusertranmax":"最大可转入",
     "subuseroutmax":"最大可转出",
     "youfreezebymaster":"您的账户已被母账户冻结",
     "youfreezebymasterxia":"下单失败，您的账户已被母账户冻结",
     "youfreezebymastercancel":"撤单失败，您的账户已被母账户冻结",
     
	"buynewvalue":"买入金额",
    "sellnetamount":"卖出数量",
    "buysellingprice":"价格",
    "buysellamount":"数量",
    "buyselltotalprice":"金额",
    "rechargeselectcurrency":"请选择充值币种",
    "rechargeonlylevel2":"非等级2用户不能通过此方式充值",
    "rechargeeurmorethan100":"欧元充值不能超过100欧元",
    "rechargehufmorethan50w":"福林充值不能超过50万",

    "tradeorderbuyalert":"您的委托价格大于最新成交价2%，是否确定下单？",
    "tradeordersellalert":"您的委托价格低于最新成交价2%，是否确定下单？",
    "weixinqrcode":"微信扫描二维码开启微信交易",
    "peopleunder18":"平台暂不支持18周岁以下人士交易",
    
    "notsupport20xleveforltc":"LTC暂不支持20倍开仓",
    "confirmation":"下单确认",
    "marketreminder":"市价全平提示",
    "accountdoesnotexist":"用户不存在！",
    "userfutureaccountfrozen":"用户合约账户被冻结！",
    "errorinselectingfinancial":"修改杠杆比例倍数错误！",
    "selectedcurrencyincorrect":"您修改的币种错误",
    "maximumadditionalamount":"最多可增加 ",
    "priceaftermarginaddition":"增加后强平价格 ",
    "maximumdecrease":"最多可减少 ",
    "margincallafterdecrease":"减少后强平价格 ",
    "transfersuccess":"转账成功！",
    "nextweekly":"次周",
    "totalmonthly":"全月",
    "quarterly":"季度",

    "tradesmallamountmore":"小额委托（<0.5BTC)的未成交委托数量不得大于50个",
    
    "tradingaccountnew":"现货交易账户",
    "futuresaccountnew":"合约交易账户",
    "fundsaccountnew":"联合理财账户",
    "marginaccountnew":"放款账户",
    "lendingaccountnew":"P2P放贷账户",
    "cantransfer":"可转：",
    "cantransferout":"可转出：",
    "pleaseselecttransferoutccount":"请选择转出账户",
    "pleaseselecttransferinccount":"请选择转入账户",
    "pleaseselecttransfercurrency":"请选择划转币种",
    "transferamountexceedavailablebalance":"您输入的金额超过最大可划转金额",
    "transferamountinvalid":"择划金额输入不正确，请输入大于0的数字",
    "yourtransferamountexceedslimit":"您输入的金额超过最大可划转金额，请重新输入划转金额",
    "transferring":"正在划转···",
    "transfercompleted":"划转成功！",
    "transferfailed":"划转失败！",
    "transferinvalidcurrency":"划转失败！选择币种出错。",
    "transferinvalidamount":"划转失败！输入金额出错。",
    "transferaccountfrozen":"划转失败！用户被冻结。",
    "transfersubaccountfrozen":"划转失败！子账户被冻结。",
    "otcfrozen2":"账户被冻结!",
    "sendMsgSuccess":"发送验证码成功!",
    "transferfuturesaccountfrozen":"划转失败！合约账户被冻结。",
    "transferamountexceedsbalance":"划转失败！可转出金额不足。",
    "transferexceededlimit":"划转失败！超过转账额度。",
    "transferhaveoutstandingloans":"划转失败！有借贷不能转入到联合理财账户。",
    "transferexceedsmarginlimit":"划转失败！超过联合理财账户金额最大值。",
    "transfersubaccountcannottomarginaccount":"划转失败！子账户不能转入到联合理财账户。",
    "transferhavenotenabledmarginaccount":"划转失败！尚未开通联合理财账户。",
    "transferhavenotenabledfuturesaccount":"划转失败！尚未开通合约交易账户。",
    "transferhavenotenabledfundsaccount":"划转失败！尚未开通P2P放贷账户。",
    "transferhavenotenabledlendsaccount":"划转失败！尚未开通专户理财账户。",

    "confirm":"确定",
    "cancel":"取消",
    "sureDelete":"您确定要删除该回复吗？一旦删除不可恢复！",
    "Yes":"确定删除",
    "No":"不删除",
    "emptyReply":"对不起！您还没有填写任何回复内容",
    "sureDeleteTheme":"您确定要删除该贴吗？一旦删除不可恢复！",
    "deleteError":"删除失败！",
    "loginFirstly":"请先登录",
    "useemailfindpassword":"您已经绑定邮箱，请使用邮箱找回密码。",
    "requestsfrequenttrylater":"请求频繁，请稍后再试。",
    "notfindthisnumber":"未找到该手机用户！",
    "wrongphonenumber":"错误的手机号码",
    "idpassportnumber":"请输入身份证/护照号码",
    "wrongsmscode":"错误的短信验证码",
    "wrongidpassportnumber":"身份证/护照号码错误",
    "requestsfrequenttry2hourslater":"操作频繁，请两小时后重试。",    
    "registerbyphone1":"请输入验证码",
    "registerbyphone2":"频繁请求发送短信，请稍后重试",
    "registerbyphone4":"尝试次数过多，请您24个小时之后再验证手机!",
    "codeexpiredtryagain":"验证码已经失效，请刷新验证码",
    "wrongcodetryagain":"验证码错误，请重新输入",
    "signupfailed":"注册失败",
    "pleaseselectthecountrycode":"请选择您的手机地区编码",
    "bindemailhavaempty":"邮箱，资金密码，验证码为空",
    "mustlinkemailbeforesyncing":"未绑定邮箱不能同步。",
    "signupregisteredphonetoomanytimes":"您输入的手机号冲突次数过多，两小时内不在进行冲突校验",
    "signupregisteredemailtoomanytimes":"您输入的邮箱地址冲突次数过多，两小时内不在进行冲突校验",
    "refresh":"刷新",
    "msgfailandpleaserefresh":"短信发送失败，请刷新页面后重试",

    "weak":"弱",
    "middle":"中",
    "strong":"强",

    "market_entrust_amount":"委托数量",
    "market_entrust_havedeal":"已成交",
    "market_entrust_price":"委托价格",
    "market_entrust_dealprice":"成交均价",
    "market_entrust_undeal":"未成交",
    "market_entrust_dealing":"成交中",
    "market_entrust_pleasefillamount":"请输入数量",

    "marekt_future_direction":"方向",
    "market_future_holding":"持仓量",
    "market_future_priceAvg":"开仓均价",
    "market_future_close_price":"平仓价",
    "market_future_leverage":"杠杆倍数",
    "market_future_available_amount":"可平量",
    "market_future_close_amount":"平仓量",
    "market_future_trade_type":"交易类型",
    "market_future_entrust_fee":"手续费",
    "market_future_entrust_margin":"保证金",
    "market_future_flat_price":"强平价格",
    
    "antiphishing1":"设置防钓鱼码",
    "antiphishing2":"修改防钓鱼码",
    "antiphishing3":"请输入防钓鱼码",
    "antiphishing4":"防钓鱼码长度不能小于1位",
    "antiphishing5":"防钓鱼码长度不能超过20位",
    "antiphishing6":"您尚未绑定邮箱",
    "antiphishing7":"防钓鱼码设置成功",
    "antiphishing8":"防钓鱼码设置失败",
    "antiphishing9":"防钓鱼码不正确",

    "maxOcoBuyOpenAmount":"最大委托金额为1,000,000",
    "minOcoBuyOpenAmount":"最小委托金额为100",
    "ocoBuyOpenAmountRange":"委托金额范围为：100 - 1,000,000",
    "maxOcoSellBtcOpenAmount" : "最大委托数量为1,000",
    "minOcoSellBtcOpenAmount" : "最小委托数量为0.01",
    "maxOcoSellLtcOpenAmount" : "最大委托数量为100,000",
    "minOcoSellLtcOpenAmount" : "最小委托数量为0.1",
    "maxOcoBuySpTriggerPrice" : "最高止盈触发价为100,000",
    "maxOcoBuySlTriggerPrice" : "最高止损触发价为100,000",
    "maxOcoSellSpTriggerPrice" : "最高止盈触发价为100,000",
    "maxOcoSellSlTriggerPrice" : "最高止损触发价为100,000",
    "maxOcoBuySpPrice" : "最高止盈委托价为100,000",
    "maxOcoBuySlPrice" : "最高止损委托价为100,000",
    "maxOcoSellSpPrice" : "最高止盈委托价为100,000",
    "maxOcoSellSlPrice" : "最高止损委托价为100,000",
    "openAmountEmpty" : "委托数量为空，请输入",
    "spTriggerPriceEmpty" : "止盈触发价为空，请输入",
    "slTriggerPriceEmpty" : "止损触发价为空，请输入",
    "spPriceEmpty" : "止盈委托价为空，请输入",
    "slPriceEmpty" : "止损委托价为空，请输入",
    "ocoOpenAmountBigger" : "可用@不足，请修改委托数量",
    "ocoMinOpenAmount" : "最小委托数量为100",
    "ocoBtcOpenAmountBigger" : "可用BTC不足，请修改委托数量",
    "ocoLtcOpenAmountBigger" : "可用LTC不足，请修改委托数量",
    "ocoSpTriggerPriceHigher" : "止损触发价需高于止盈触发价",
    "ocoSlTriggerPriceHigher" : "止盈触发价需高于止损触发价",
    "spPriceRange" : "止盈委托价范围为：0.01 - 100000",
    "slPriceRange" : "止损委托价范围为：0.01 - 100000",
    "buySpTriggerPriceRange" : "止盈触发价范围为：0.01 - 最新成交价",
    "buySlTriggerPriceRange" : "止损触发价范围为：最新成交价 - 100000",

    "sellSpTriggerPriceRange" : "止盈触发价范围为：最新成交价 - 100000",
    "sellSlTriggerPriceRange" : "止损触发价范围为：0.01 - 最新成交价",

    "turnover" : "成交均价",
    
    "app_word1" : "二维码失效，请",
    "app_word2" : "刷新二维码",
    "app_word3" : "扫描成功",
    "app_word4" : "请用微信扫描二维码登录",
    "app_word5" : "获得二维码失效，请",
    "app_word6" : "重新刷新",
    "app_word7" : "您已经登录了",
    "app_word8" : "微信二维码失效，请",
    "app_word9" : "刷新",
    "app_word10" : "请用App扫描二维码登录",
    "app_word11" : "回到登录页",
    "app_word12" : "您已经绑定账号了，请重新扫描二维码登录",
    "app_word13" : "微信注册失败",
    "app_word14" : "微信二维码已经失效，请重新扫描登录",
    "app_word15" : "您已经绑定账号了",
    "app_word16" : "该账号已经绑定过微信了",
    "app_word17" : "绑定失败，请稍后重试或联系客服",
    "app_word18" : "登录失败",

    "enterpriseContact1" : "姓氏不能为空",
    "enterpriseContact2" : "姓氏过长",
    "enterpriseContact3" : "名字不能为空",
    "enterpriseContact4" : "名字过长",
    "enterpriseContact5" : "公司名称不能为空",
    "enterpriseContact6" : "公司名称过长",
    "enterpriseContact7" : "邮箱或者手机号码请至少填写一个",
    "enterpriseContact8" : "邮箱地址过长",
    "enterpriseContact9" : "请检查邮箱格式",
    "enterpriseContact10" : "手机号码过长",
    "enterpriseContact11" : "请检查手机号码",
    "enterpriseContact12" : "提交操作过于频繁，请明日再试",
    "enterpriseContact13" : "提交成功",
    "enterpriseContact14" : "提交失败",
    
    "maxOtcPrice" : "最大委托价为1,000,000",
    "minOtcPrice" : "最小委托价格为0.01",
    "maxOtcAmount" : "最大委托数量为1,000,000",
    "minOtcAmount" : "最小委托数量为",
    "otcPriceEmpty" : "委托价格为空，请输入",
    "otcAmountEmpty" : "委托数量为空，请输入",
    "otcTurnoverEmpty" : "委托金额为空，请输入",
    "cnyBalanceInsufficient" : "可用@不足，请修改委托数量",
    "coinBalanceInsufficient0" : "BTC余额不足,请修改委托数量",
    "coinBalanceInsufficient1" : "LTC余额不足,请修改委托数量",
    "otcOrderNotExist" : "此委托已不存在!",
    "otcOrderTypeError" : "此委托的买卖类型不对应!",
    "keyError" : "订单为私密订单， 密钥错误",
    "otcBuy" : "确认买入",
    "otcSell" : "确认卖出",
    "keyRequired" : "秘钥不能为空!",
    "keyIsError" : "秘钥错误请重新输入!您还有$time次机会!",
    "keyIsError2" : "秘钥错误请重新输入!",
    "tryAfter2Hours" : "错误超过5次,两个小时后重试!",
    "otcOrderCanceled" : "订单被撤销!",
    "freezeWithdraw" : "您的提现功能被冻结，请联系客服!",
    "specialIntercept" : "系统检测到您有可疑操作，暂时不可进行大宗交易!",

    "errorSymbol" : "币种错误！",
    "errorParams" : "参数错误！",
    
    "withdrawaladdress1" : "请选择账户类型",
    "withdrawaladdress2" : "账户保护，不能添加修改认证地址",
    "withdrawaladdress3" : "目标账户登录名为空",
    "withdrawaladdress4" : "账户类型未选择",
    "withdrawaladdress5" : "账户错误，请再次核对！",
    "withdrawaladdress6" : "不能重复绑定",
    "withdrawaladdress7" : "绑定账号错误次数过多，请24小时后重试"

};
var ALL_AUTHORITY = [["4","大宗交易"], ["2","提币"], ["1", "交易"]]; //权限值从大到小